# Generated by Django 6.0.5 on 2026-05-20 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('dia_inteiro', models.BooleanField(default=False)),
                ('visibilidade', models.CharField(choices=[('partilhado', 'Partilhado'), ('pessoal', 'Pessoal')], default='partilhado', max_length=20)),
                ('cor', models.CharField(default='#5C6BC0', max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.household')),
                ('pertence_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_pessoais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio'],
            },
        ),
    ]
