# Generated by Django 6.0.5 on 2026-05-20 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('alimentacao', 'Alimentação'), ('transportes', 'Transportes'), ('casa', 'Casa'), ('saude', 'Saúde'), ('lazer', 'Lazer'), ('vestuario', 'Vestuário'), ('viagem', 'Viagem'), ('subscricoes', 'Subscrições'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('data', models.DateField()),
                ('divisao', models.CharField(choices=[('50_50', '50/50'), ('total_a', 'Pago por mim (total)'), ('total_b', 'Pago pelo parceiro (total)'), ('personalizado', 'Personalizado')], default='50_50', max_length=20)),
                ('valor_pessoa_a', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pessoa_b', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_criadas', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='core.household')),
                ('pago_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_pagas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Liquidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacoes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacoes', to='core.household')),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacoes_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidação',
                'verbose_name_plural': 'Liquidações',
                'ordering': ['-data'],
            },
        ),
    ]
