# Generated by Django 6.0.5 on 2026-05-20 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('financeiro', 'Financeiro'), ('viagem', 'Viagem'), ('casa', 'Casa'), ('pessoal', 'Pessoal'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('valor_meta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ativo', 'Ativo'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_criados', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='core.household')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
