# Generated by Django 6.0.5 on 2026-05-20 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('unidade', models.CharField(default='un', max_length=50)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemListaCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantidade', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(choices=[('frescos', 'Frescos'), ('lacticinios', 'Lacticínios'), ('carnes', 'Carnes e Peixes'), ('padaria', 'Padaria'), ('conservas', 'Conservas'), ('bebidas', 'Bebidas'), ('higiene', 'Higiene'), ('limpeza', 'Limpeza'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('comprado', models.BooleanField(default=False)),
                ('comprado_em', models.DateTimeField(blank=True, null=True)),
                ('gerado_automaticamente', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comprado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_feitas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_criados', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_compras', to='core.household')),
            ],
            options={
                'verbose_name': 'Item da Lista de Compras',
                'verbose_name_plural': 'Lista de Compras',
                'ordering': ['comprado', 'categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('pequeno_almoco', 'Pequeno-almoço'), ('almoco', 'Almoço'), ('jantar', 'Jantar'), ('snack', 'Snack')], default='jantar', max_length=20)),
                ('receita', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='core.household')),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
                'ordering': ['data', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='RefeicaoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refeicoes.ingrediente')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refeicoes.refeicao')),
            ],
            options={
                'verbose_name': 'Ingrediente da Refeição',
                'unique_together': {('refeicao', 'ingrediente')},
            },
        ),
        migrations.AddField(
            model_name='refeicao',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, through='refeicoes.RefeicaoIngrediente', to='refeicoes.ingrediente'),
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('minimo_stock', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='core.household')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refeicoes.ingrediente')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Inventário',
                'ordering': ['ingrediente__nome'],
                'unique_together': {('household', 'ingrediente')},
            },
        ),
    ]
