# Generated by Django 6.0.5 on 2026-05-20 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('restaurante', 'Restaurante'), ('museu', 'Museu / Exposição'), ('concerto', 'Concerto / Espetáculo'), ('viagem', 'Viagem'), ('cinema', 'Cinema'), ('desporto', 'Desporto'), ('natureza', 'Natureza / Outdoor'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('estado', models.CharField(choices=[('wishlist', 'Wishlist'), ('planeado', 'Planeado'), ('feito', 'Feito')], default='wishlist', max_length=20)),
                ('data_planeada', models.DateField(blank=True, null=True)),
                ('data_realizada', models.DateField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('avaliacao_a', models.IntegerField(blank=True, null=True)),
                ('avaliacao_b', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_criadas', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.household')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-criado_em'],
            },
        ),
    ]
